# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probes',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specification',
            name='interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specification',
            name='one_off',
            field=models.BooleanField(default=True),
        ),
    ]
