# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_auto_20160731_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='start_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='specification',
            name='stop_time',
            field=models.DateField(),
        ),
    ]
