# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20160731_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='start_time',
            field=models.DateField(),
        ),
    ]
