# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20160801_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
