# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_auto_20160801_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='msm_id',
            field=models.IntegerField(default=0),
        ),
    ]
