# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0009_auto_20160802_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='status',
            field=models.CharField(default='Running', max_length=10),
        ),
    ]
