# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_specification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='status',
        ),
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(default='Running', max_length=10),
        ),
    ]
