# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0013_traceroute12'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traceroute1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ManyToManyField(to='measurement.Countries')),
            ],
        ),
    ]
