# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0015_traceroute2'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceroute1',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='traceroute12',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='traceroute2',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
