# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0017_auto_20160919_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.RemoveField(
            model_name='traceroute1',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='traceroute2',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='traceroute12',
            name='countries',
        ),
        migrations.AlterField(
            model_name='traceroute12',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Traceroute1',
        ),
        migrations.DeleteModel(
            name='Traceroute2',
        ),
        migrations.AddField(
            model_name='relation12',
            name='traceroute12',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroute12'),
        ),
    ]
