# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0019_auto_20160920_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceroute12',
            name='countries',
            field=models.ManyToManyField(through='measurement.Relation12', to='measurement.Countries'),
        ),
    ]
