# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0021_auto_20160926_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Relation9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation1', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation10', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation11', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation13', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation14', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation2', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation3', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation4', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation5', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation6', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation7', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation8', to='measurement.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Traceroutemeasurement9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('countries', models.ManyToManyField(through='measurement.Relation9', to='measurement.Countries')),
            ],
        ),
        migrations.RenameField(
            model_name='relation12',
            old_name='traceroutemeasurement12',
            new_name='traceroutemeasurement',
        ),
        migrations.AlterField(
            model_name='traceroutemeasurement12',
            name='countries',
            field=models.ManyToManyField(through='measurement.Relation12', to='measurement.Countries'),
        ),
        migrations.AddField(
            model_name='relation9',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement9'),
        ),
        migrations.AddField(
            model_name='relation8',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement8'),
        ),
        migrations.AddField(
            model_name='relation7',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement7'),
        ),
        migrations.AddField(
            model_name='relation6',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement6'),
        ),
        migrations.AddField(
            model_name='relation5',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement5'),
        ),
        migrations.AddField(
            model_name='relation4',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement4'),
        ),
        migrations.AddField(
            model_name='relation3',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement3'),
        ),
        migrations.AddField(
            model_name='relation2',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement2'),
        ),
        migrations.AddField(
            model_name='relation14',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement14'),
        ),
        migrations.AddField(
            model_name='relation13',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement13'),
        ),
        migrations.AddField(
            model_name='relation11',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement11'),
        ),
        migrations.AddField(
            model_name='relation10',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement10'),
        ),
        migrations.AddField(
            model_name='relation1',
            name='traceroutemeasurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Traceroutemeasurement1'),
        ),
    ]
