# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0022_auto_20161024_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traceroutemeasurement12',
            name='countries',
            field=models.ManyToManyField(through='measurement.Relation12', to='measurement.Countries'),
        ),
    ]
